1. SELECT BOOK_NAME, COST FROM BOOKS_00028 WHERE COST = (SELECT MAX(COST) 
FROM BOOKS_00028);
2. SELECT MIN(COST) AS MIN_COST, AVG(COST) AS AVG_COST, SUM(COST) AS TOTAL_COST 
FROM BOOKS_00028;
3. SELECT MEMBER_NAME , MEMBER_ID FROM MEMBER_00028 WHERE MEMBER_ID 
IN(SELECT MEMBER_ID FROM ISSUE_00028 WHERE ISSUE_DATE BETWEEN DATE '2011-01
26' AND DATE '2011-04-14')
4. SELECT BOOK_NAME, AUTHOR_NAME, CATEGORY FROM BOOKS_00028 WHERE 
CATEGORY <> 'OTHERS';
5A.a. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME 
LIKE '____t%'
5A.b. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME 
LIKE 'S%';
5A.c. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME 
LIKE 'S_%'
5A.d. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME 
LIKE '%a';
5A.e. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE 
SUBSTR(AUTHOR_NAME,3,1)='a' AND SUBSTR(AUTHOR_NAME,5,1)='a';
5A.f. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE 
SUBSTR(AUTHOR_NAME,-2,1)='a';
5A.g. SELECT BOOK_NAME, AUTHOR_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME 
LIKE 'D%E';
5B.h. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE MEMBER_NAME LIKE 'S%';
5B.i. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE (MEMBER_NAME LIKE 'S%' OR 
MEMBER_NAME LIKE 'A%') AND MEMBER_NAME LIKE '%t%';
5C. SELECT BOOK_NAME FROM BOOKS_00028 WHERE BOOK_NAME LIKE '%SQL%';
6. SELECT COUNT(*) FROM BOOKS_00028 WHERE COST > 350;
7. SELECT COUNT(DISTINCT AUTHOR_NAME) FROM BOOKS_00028;
8.a. SELECT ABS(-167) FROM DUAL;
8.b. SELECT POWER(8,6) FROM DUAL;
8.c. SELECT ROUND(134.56789,2) FROM DUAL;
8.d. SELECT SQRT(144) FROM DUAL;
8.e.  SELECT FLOOR(13.15), CEIL(13.15) FROM DUAL;
9.SELECT EXTRACT(YEAR FROM SYSDATE), EXTRACT(MONTH FROM SYSDATE), 
EXTRACT(DAY FROM SYSDATE) FROM DUAL;
10. SELECT GREATEST(4,5,17) FROM DUAL;
11. SELECT LEAST(4,5,17) FROM DUAL;
12. SELECT SUBSTR('INFOSYS',3,4) FROM DUAL;
13. SELECT ASCII('A'), ASCII('S') FROM DUAL;
14. SELECT LENGTH('INFOSYS'), REPLACE('INFOSYS','S','T') FROM DUAL;
15. SELECT MEMBER_NAME, MEMBER_ADDRESS FROM MEMBER_00028 WHERE 
MEMBER_ADDRESS='Kolkata';
16. SELECT BOOK_NAME FROM BOOKS_00028 WHERE COST BETWEEN 300 AND 500;
17. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE 
MEMBERSHIP_TYPE='HALFYEARLY';
18. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE EXTRACT(YEAR FROM 
ACC_OPEN_DATE)=2011;
19. SELECT PENALTY_AMOUNT FROM MEMBER_00028 WHERE MEMBER_ID IN(SELECT 
MEMBER_ID FROM ISSUE_00028 WHERE BOOK_NO IN(SELECT BOOK_NO FROM 
BOOKS_00028 WHERE BOOK_NAME ='Let us C'))
20. SELECT MAX_BOOK_ALLOWED FROM MEMBER_00028 WHERE MEMBER_ID IN(SELECT 
MEMBER_ID FROM ISSUE_00028 WHERE ISSUE_DATE BETWEEN DATE '2011-01-01' AND 
DATE '2011-01-31')
21. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE MEMBER_ID NOT IN (SELECT 
MEMBER_ID FROM ISSUE_00028);
22. SELECT BOOK_NAME, CATEGORY FROM BOOKS_00028 WHERE COST IS NULL;
23. SELECT BOOK_NAME FROM BOOKS_00028 WHERE AUTHOR_NAME='Loni' AND 
COST<600;
24. SELECT * FROM ISSUE_00028 WHERE RETURN_DATE IS NULL;
25. SELECT * FROM BOOKS_00028 WHERE CATEGORY IN ('SCIENCE','DATABASE');
26. SELECT * FROM MEMBER_00028 ORDER BY PENALTY_AMOUNT DESC;
27.SELECT * FROM BOOKS_00028 ORDER BY CATEGORY ASC, COST DESC;
28. SELECT INITCAP(BOOK_NAME), UPPER(AUTHOR_NAME) FROM BOOKS_00028 ORDER BY 
BOOK_NAME DESC;
29. SELECT BOOK_NO,BOOK_NAME,AUTHOR_NAME,COST,CASE WHEN 
CATEGORY='DATABASE' THEN 'D' WHEN CATEGORY='SCIENCE' THEN 'S' WHEN 
CATEGORY='RDBMS' THEN 'R' ELSE 'O' END AS "CATEGORY" FROM BOOKS_00028;
30. SELECT MEMBER_NAME FROM MEMBER_00028 WHERE EXTRACT(YEAR FROM 
ACC_OPEN_DATE)=2011
